Gh teams improvements
Openscapes/kyber pull request #139
Opened 2024-11-22 21:53 UTC by ateucher

Sometimes we need more metadata about a team or a member than than just the name (especially the slug, in the case of `list_team_members()`), so this allows returning a data frame of team metadata from `list_teams()` and `list_team_members()`, rather than the raw `gh` response or a character vector of names.

This is used in `list_team_members()` to validate the supplied team against the slug.

2024-11-24 22:42 UTC, seankross commented
@ateucher is this ready for review?

2024-11-25 18:04 UTC, ateucher commented
Yes, thanks @seankross!

2024-12-04 04:02 UTC, seankross requested changes
See #142

2024-12-06 00:21 UTC, seankross approved these changes

2024-12-06 01:15 UTC, ateucher commented
Thanks!

2024-12-06 01:15 UTC, merged